### ISSUE TITLE
Unable to load 4.0 using require()

### ISSUE THREAD

**Issue by bazineta** [pirelenito/git-revision-webpack-plugin#66]
After upgrading to 4.0, I can no longer load as per the documentation, i.e., require the library, call `new Plugin()`. Calling `new Plugin.default()` does work.

The library implementation has an `exports.default`, so that's not unexpected. I think you'd want a `module.exports` there instead, given that you're seemingly still going for CJS compatibility here.

**Comment by mfurniss** [comment]
After updating to 4.0.0 I'm getting this error

TypeError: GitRevisionPlugin is not a constructor

**Comment by tschmidtb51** [comment]
@pirelenito: Same problem here.

**Comment by Prior99** [comment]
Same problem here.

**Comment by pirelenito** [comment]
Thanks for the report. I'll probably have some time this week to fix the issue. 

In the meantime, sticking to 3.0.6 is recommended as a workaround.

**Comment by pirelenito** [comment]
I just pushed a patched version `v4.0.1` that fixes the issue and I'll prepare a PR to have a permanent fix for future releases.

**Comment by tschmidtb51** [comment]
I still see the error message as described in https://github.com/secvisogram/secvisogram/issues/10#issuecomment-831929359. However, the build seems to work.

**Comment by pirelenito** [comment]
I'm trying a new approach in #67, can you try a beta build that I prepared @tschmidtb51 ?

```json
"devDependencies": {
  "git-revision-webpack-plugin": "^5.0.0-1"
}
```

And change your require statement to:

```js
const { GitRevisionPlugin } = require('git-revision-webpack-plugin')
```

**Comment by tschmidtb51** [comment]
> I'm trying a new approach in #67. Can you try a beta build that I prepared @tschmidtb51 ?

I did and it worked locally and in GitHub Actions: https://github.com/secvisogram/secvisogram/pull/46

**Comment by pirelenito** [comment]
Thank you all for your help! Just released `v5.0.0` with the confirmed fix. ❤️
